version: '3.8'

services:

# no need for same docker-compose.yml, just same external docker network, or host only
  rathole:
    image: rapiz1/rathole:v0.5.0
    command: --client /config/client.toml
    restart: unless-stopped
    volumes:
      - ./rathole.client.toml:/config/client.toml:ro

networks:
  proxy:
    external: true
