[client]
remote_addr = "<ip-of-vps>:2333"
[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "<public_key>"

[client.services.traefik-http]
token = "secret_token"
local_addr = "traefik:5080"  # address for the service you want to expose

[client.services.traefik-https] # not a docker-compose.yml service, just name of tunnel
token = "secret_token"
local_addr = "traefik:5443" # this is name of d-c.yml service

