[server]
bind_addr = "0.0.0.0:2333" 

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "private_key" 

[server.services.nginx]
token = "my-secret" 
bind_addr = "0.0.0.0:5080" 
