version: '3.9'

services:
  rathole:
    image: rapiz1/rathole:v0.5.0
    command: --client /config/rathole.client.toml
    restart: unless-stopped
    volumes:
      - ./rathole.client.toml:/config/rathole.client.toml:ro
    # ports:
    #   - '8080:5080'
    networks:
      - proxy

  nginx-with-volume:
    image: nginx:stable-alpine3.17-slim
    container_name: nginx-with-volume
    restart: unless-stopped
    depends_on:
      - rathole
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - '80:8080'

    networks:
      - proxy

networks:
  proxy:
    external: true
