[client]
remote_addr = "152.70.160.21:2333" # on client ONLY this port is required

[client.transport]
type = "noise"

[client.transport.noise]
remote_public_key = "public_key"

[client.services.nginx]
token = "secret_token"
local_addr = "nginx-with-volume:8080" # expose here directly on app port, without any mapping in docker-compose.yml

# this is incorrect
# local_addr = "nginx-with-volume:5080" 

